### ISSUE TITLE
Have nicer error message if minor location contains invalid data.

### ISSUE THREAD

**Issue by Miepee** [biosp4rk/mfr_patcher#5]
if i have something like this:
```json
{
    "MinorLocations": [
        {
            "Area": 0,
            "Room": 7,
            "BlockX": 0,
            "BlockY": 14,
            "Item": "MissileTank"
        },
     ]
 }
```

It would be nicer to get a more human friendlier error message rather than just "StopIteration in next()"

**Comment by biosp4rk** [comment]
This should never cause an error for the user once the base patch is paired with the patcher, but I can add better error messages for developers
